name: kolok
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '^3.11.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.14.4"
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/

  fonts:
    - family: Gilroy
      fonts:
        - asset: assets/fonts/Gilroy-Light.otf
          weight: 300
        - asset: assets/fonts/Gilroy-ExtraBold.otf
          weight: 800

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo_kolok.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/logo_kolok.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "assets/logo_kolok.png"
    icon_size: 48 
  macos:
    generate: true
    image_path: "assets/logo_kolok.png"